<a href="https://colab.research.google.com/github/Samhithagit/Samhitha_A_1BM23CS293_ML_LAB/blob/main/1BM23CS293_Lab_6_Decision_Tree_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
data = pd.read_csv("/content/iris (1).csv")

# Features and target
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Train Test Split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# -------- ID3 (Entropy) --------
id3 = DecisionTreeClassifier(criterion="entropy")
id3.fit(X_train, y_train)

y_pred_id3 = id3.predict(X_test)

print("ID3 Accuracy:", accuracy_score(y_test, y_pred_id3))
print("ID3 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_id3))


# -------- CART (Gini) --------
cart = DecisionTreeClassifier(criterion="gini")
cart.fit(X_train, y_train)

y_pred_cart = cart.predict(X_test)

print("\nCART Accuracy:", accuracy_score(y_test, y_pred_cart))
print("CART Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_cart))

ID3 Accuracy: 1.0
ID3 Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

CART Accuracy: 1.0
CART Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
data = pd.read_csv("/content/drug.csv")

# Encode categorical columns
le = LabelEncoder()
data['Sex'] = le.fit_transform(data['Sex'])
data['BP'] = le.fit_transform(data['BP'])
data['Cholesterol'] = le.fit_transform(data['Cholesterol'])
data['Drug'] = le.fit_transform(data['Drug'])

# Features and target
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Train test split (80 / 20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# -------- ID3 (Entropy) --------
id3 = DecisionTreeClassifier(criterion='entropy')
id3.fit(X_train, y_train)

pred_id3 = id3.predict(X_test)

print("ID3 Accuracy:", accuracy_score(y_test, pred_id3))
print("ID3 Confusion Matrix:")
print(confusion_matrix(y_test, pred_id3))


# -------- CART (Gini) --------
cart = DecisionTreeClassifier(criterion='gini')
cart.fit(X_train, y_train)

pred_cart = cart.predict(X_test)

print("\nCART Accuracy:", accuracy_score(y_test, pred_cart))
print("CART Confusion Matrix:")
print(confusion_matrix(y_test, pred_cart))

ID3 Accuracy: 0.975
ID3 Confusion Matrix:
[[ 5  0  0  0  0]
 [ 1  6  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0 13  0]
 [ 0  0  0  0 12]]

CART Accuracy: 0.975
CART Confusion Matrix:
[[ 5  0  0  0  0]
 [ 1  6  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0 13  0]
 [ 0  0  0  0 12]]


In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Load dataset
data = pd.read_csv("/content/petrol_consumption.csv")

# Features and target
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Train Test Split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# -------- Regression Tree Model 1 (CART - Squared Error) --------
model1 = DecisionTreeRegressor(criterion="squared_error")
model1.fit(X_train, y_train)

pred1 = model1.predict(X_test)

mae1 = mean_absolute_error(y_test, pred1)
mse1 = mean_squared_error(y_test, pred1)
rmse1 = np.sqrt(mse1)

print("Regression Tree (Squared Error)")
print("MAE:", mae1)
print("MSE:", mse1)
print("RMSE:", rmse1)

Regression Tree (Squared Error)
MAE: 91.6
MSE: 17140.6
RMSE: 130.9221142511837
